version: 2
registries:
  hex-organization-coingaming:
    type: hex-organization
    organization: coingaming
    key: "${{secrets.HEX_ORGANIZATION_COINGAMING_KEY}}"

updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  registries:
  - hex-organization-coingaming
