# Generated with `mix gen.currency.config`
use Mix.Config
config :money,
  currency_config:
  [%{code: "BTC",
   display: %{code: "mBTC",
     inputPrecision: 5,
     name: "Bitcoin (millis)",
     precision: 4,
     shift: 3,
     symbol: "m₿"},
   precision: 8},
 %{code: "EUR",
   display: %{code: "EUR",
     inputPrecision: 4,
     name: "Euro",
     precision: 2,
     shift: 0,
     symbol: "€"},
   precision: 5},
 %{code: "USD",
   display: %{code: "USD",
     inputPrecision: 4,
     name: "United States dollar",
     precision: 2,
     shift: 0,
     symbol: "$"},
   precision: 5},
 %{code: "GBP",
   display: %{code: "GBP",
     inputPrecision: 4,
     name: "Pound sterling",
     precision: 2,
     shift: 0,
     symbol: "£"},
   precision: 5},
 %{code: "AUD",
   display: %{code: "AUD",
     inputPrecision: 4,
     name: "Australian dollar",
     precision: 2,
     shift: 0,
     symbol: "A$"},
   precision: 5},
 %{code: "HKD",
   display: %{code: "HKD",
     inputPrecision: 4,
     name: "Hong Kong dollar",
     precision: 2,
     shift: 0,
     symbol: "HK$"},
   precision: 5},
 %{code: "JPY",
   display: %{code: "JPY",
     inputPrecision: 4,
     name: "Japanese yen",
     precision: 2,
     shift: 0,
     symbol: "¥"},
   precision: 5},
 %{code: "PHP",
   display: %{code: "PHP",
     inputPrecision: 4,
     name: "Philippine peso",
     precision: 2,
     shift: 0,
     symbol: "₱"},
   precision: 5}]
